### ISSUE TITLE
-m parameter partly works

### ISSUE THREAD

**Issue by GustavHaapalahti** [MmAaXx500/dt-move#2]
I just tried this script and I love it!

I found something strange with the directory renamer though.
All my old paths start with
Z:\data
but if i make a pathmap file with that it does not replace anything.
If I  use the following (which all of the paths also start with)
Z:\data\documents
It accepts most paths but 5 of the hundreds of paths I have are not accepted and have to be mapped separately for some reason.
```
paths that will NOT be rewritten:

        Z:\data\documents\playmemories-a7ii\2021-03-20\norrsken_timelapse
        Z:\data\documents\lens-calibration\lensfun-tamron-28-200\run2\vignetting
        Z:\data\documents\sony-a7iv\2023-01-22-komet\iso12800-5s-600mm
        Z:\data\documents\sony-a7iv\2023-01-28-komet\iso3200-15s-600mm
        Z:\data\documents\sony-a7iv\2023-10-30-astro-moon\moon_multi

paths that will be rewritten:
        Z:\data\documents
        -> /mnt/raid/data/documents

```

**Comment by GustavHaapalahti** [comment]
After looking a bit more at the results, the paths that "will not be written" are added as separate film rolls but are subdirectoreis to other film rolls.
After just pressing "ok" and ignoring the missing paths they seem to be correct anyway in the converted database.

**Comment by MmAaXx500** [comment]
Thanks for opening this issue!

I suspect the filtering of the paths are a bit broken in case of `Z:\data\documents`. Can you confirm that running with `--nofilter` gives the correct list of rewritten and not rewritten paths in case of `Z:\data` and `Z:\data\documents` ?

Initially, the `Z:\data` did nothing because it was filtered out (this is intended). I'm thinking about disabling filtering if a pathmap is used to avoid this unexpected behavior.

**Comment by GustavHaapalahti** [comment]
You are right. With the --nofilter flag everything works correctly. Seems like it is only the directory grouping that is a bit wonky.

**Comment by MmAaXx500** [comment]
Pushed some commits, it should be ok now.

Fixed how the suggested path are generated, they should be ok now if no pathmap is used.
Turned off the filtering if pathmap is used (`--nofilter` is no longer necessary).

**Comment by GustavHaapalahti** [comment]
Thank you. Everything seems to work as expected now :-)
